### ISSUE TITLE
eliter::elite.network og soc.elite::elite.network giver forskellige resultater

### ISSUE THREAD

**Issue by Taarnborg** [antongrau/eliter#4]
Hej Anton.

Nadia og jeg opdagede lige at vi fik præcis 130 flere personer i kernen, hvis vi lavede netværket med eliter og ikke med soc.elite.

Test det selv efter:

**med soc.elite:**
pacman::p_load(igraph,eliter,soc.elite)

den   <- eliter::eliteDB_den(user = BRUGER , pass = KODE)
den16 <- den[is.na(den$ARCHIVED),]
den16 <- den16[!duplicated(den16[,c("NAME", "AFFILIATION")]),]
rm(den)

net.all                  <- soc.elite::elite.network(den16, sigma = 14)
net.com                 <- soc.elite::largest.component(net.all, cut.off = 1)
sp                      <- igraph::shortest.paths(net.com)
sp2                     <- sp <= 2.1 * 1
net.sp                  <- igraph::graph.adjacency(sp2, mode="undirected", diag=FALSE)
core.sp                 <- igraph::graph.coreness(net.sp)
kore                    <- core.sp == max(core.sp)
sec                     <- vector(length = vcount(net.com))
sum(kore)

**med eliter:**
pacman::p_load(igraph,eliter,soc.elite)

den   <- eliter::eliteDB_den(user = BRUGER , pass = KODE)
den16 <- den[is.na(den$ARCHIVED),]
den16 <- den16[!duplicated(den16[,c("NAME", "AFFILIATION")]),]
rm(den)

net.all                 <- eliter::elite.network(den16, sigma = 14)
net.com                 <- soc.elite::largest.component(net.all, cut.off = 1)
sp                      <- igraph::shortest.paths(net.com)
sp2                     <- sp <= 2.1 * 1
net.sp                  <- igraph::graph.adjacency(sp2, mode="undirected", diag=FALSE)
core.sp                 <- igraph::graph.coreness(net.sp)
kore                    <- core.sp == max(core.sp)
sec                     <- vector(length = vcount(net.com))
sum(kore)

**Comment by antongrau** [comment]
Hej Ronnie,

Det er også forventeligt da soc.elite::elite.network stadig vægter de indlejrede affiliations. Det er fjernet i eliter. Vi regner med at ændre tilgangen til at finde kernen og vil nu bruge betweenness.decomposition til at finde linkers og det  gør testen for indlejrede mindre vigtig. Men egentlig burde der ikke være så stor forskel. Det får mig til at tro at der også ligger noget ekstra i vægtningen.

**Comment by Taarnborg** [comment]
Hej Anton.

Det giver mening - hvis vi skulle lave en tentativ kerne ville du så anbefale at vi:

1. Bruger soc.elite til at lave netværket, og så antager at det er nogenlunde de samme organisationer, der vil være indlejret i hinanden.

2. Laver netværket med eliter, og laver en betweenness.decomposition med max.path og estimate min parametereren sat til default, for derefter at køre graph.coreness

3. Det samme som #2 men med max.path og estimate.min sat til fx 3 og 5. Og så evt køre graph.coreness efterfølgende

**Comment by antongrau** [comment]
Jeg tror vi må opgive at lave sammenlignelige analyser af de to datasæt, ihvertfald lige i øjeblikket, fordi vi ikke har nok baller og events - samtidig har vi fået adgang til en masse nye datakilder som det ville være oplagt at tage med, så samlet set må vi nok lave et brud. Til det brud så tror jeg mere på det nye approach. Så mit bud er 2.
